### ISSUE TITLE
checking for maxminddb.h... no - failing install

### ISSUE THREAD

**Issue by whoteaches** [desuwa/hive_geoip2#2]
Hi there.
I upgraded to ruby 2.3.0
Installed bundler and installed my gemset from my rails app
hive_geoip2 fails because it cannot find maxminddb.h

It's looking inside /Users/me/.rvm/gems/ruby-2.3.0/gems/hive_geoip2-0.1.2/ext/hive_geoip2
/Users/me/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160120-32274-1551slx.rb extconf.rb

which is essentially /Users/me/.rvm/gems/ruby-2.3.0/gems/hive_geoip2-0.1.2/ext/hive_geoip2

I already used brew to install libmaxminddb

When I search for maxminddb.h with find /usr/local/include /usr/include -name maxminddb.h, I get:
/usr/local/include/maxminddb.h
find: /usr/include: No such file or directory

So it's inside my /usr/local/include

How do I resolve this issue?

**Comment by desuwa** [comment]
Try passing mmdb location manually:

```
gem install hive_geoip2 -- --with-maxminddb-dir=/usr/local
```

**Comment by whoteaches** [comment]
Thanks! That worked.
